keys:
    - &linus_age age15x3r5c7z9v6fmzqyckv04zv7f62xuk7xf0xyat2kn2udsz8l99dq3wypmr
    - &laptop_ssh age1czsdra4zhheftr6kuwze4rl6jm4z75y9f4hed3ukxn2zwe5gnpjsneger3
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *linus_age
      - *laptop_ssh